name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Rust
      run: rustup update
    - name: Get binstall
      run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - name: Get dioxus
      run: cargo binstall -y dioxus-cli
    - name: Environment details
      run: |
        rustup toolchain list
        dx --version
    - name: Build
      run: dx bundle
    - name: Upload macOS DMG
      uses: actions/upload-artifact@v4
      with:
        name: dx-desktop-macOS
        path: /Users/runner/work/dx-desktop/dx-desktop/target/dx/dx-desktop/bundle/macos/bundle/dmg/DxDesktop_0.1.0_aarch64.dmg
    - name: Upload macOS Bundle Folder
      uses: actions/upload-artifact@v4
      with:
        name: dx-desktop-macOS
        path: /Users/runner/work/dx-desktop/dx-desktop/target/dx/dx-desktop/bundle/macos/bundle/macos/DxDesktop.app
        
